MiniShibaInu/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

handler400 = 'scanner.views.handler404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scanner.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

scanner/urls.py
from scanner.views import home, scanner
from django.urls import path


app_name = "scan"

urlpatterns = [
    path('',home,name="scanner"),
    path('scan',scanner.as_view(),name="detail_account_address"),
    path('scan/<slug:search>',scanner.as_view(),name="detail_account_address")
]

scanner/models.py
from django.db import models
from django.db.models import query

class get_query(models.Manager):
    def network(self,data):
        change_query = self.filter(name=data)
        for i in change_query:
            net =  i.query
        return net

# Create your models here.
class Network(models.Model):
         network = models.CharField(max_length=10,verbose_name="Network")

         def __str__(self):
             return self.network

class Query(models.Model):
         name = models.CharField(max_length=10)
         query = models.TextField(verbose_name="data")

         def __str__(self):
             return self.name

         objects = get_query() 

scanner/views.py
from .mixins import CHNetwork, Redirect
from django.shortcuts import render
from django.views.generic import ListView
from .models import  Query
import time,requests
from .utils import get_tron_balance
from django.template import RequestContext


def handler404(request,exception):
    context = {}
    response = render(request, "404.html", context=context)
    response.status_code = 404
    return response


def home(request):
  response = requests.get("https://api.pancakeswap.info/api/v2/tokens/0xeb35acbd23cf9d1c13d276815b9969effc5c878f").json()['data']['price']
  return render(request,"home.html",{"response":response})



class scanner(Redirect,CHNetwork,ListView):
    template_name = "detail_address_token.html"
    query = []
    network = "ethereum" #deafult
    headers = {'X-API-KEY': 'BQYTMdjncNjDJ2MoWuu1NpHG6SGtnd1f'}
    # def get_queryset(self):
    #     self.query
    #     return self.query
    def get_queryset(self):
        global headers,search
        search = self.kwargs.get("search")
        headers = self.headers ; queryset =  self.query
        return queryset


    def get_context_data(self, *args, **kwargs):
        n = time.time()
        # url = "https://api.bscscan.com/api?module=account&action=txlist&address=%s&startblock=0&endblock=99999999&page=1&offset=10&sort=asc&apikey=8KVAI7FBADXY11Z9YR1KQGCGU5Z7PEGG4B"%search
        context = super().get_context_data(*args, **kwargs)
        eth_networks = ["matic","ethereum"]
        if self.network == "ethereum":
        #   for network in eth_networks:
        #     query = Query.objects.network("ethereum")%(network,search)
        #     context[network] =  requests.post('https://graphql.bitquery.io/',json={'query': query}, headers=headers).json()
            query = Query.objects.network("eth_t")%("bsc",search,search)
            context['transaction'] = requests.post('https://graphql.bitquery.io/',json={'query': query}, headers=headers).json()["data"]["ethereum"]
        elif self.network == "tron":
              get_tron_balance(search)
              context['balance'] = list(get_tron_balance(search))
        return context

templates/assets.html
{% load static %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'detail/css/table.css' %}">
<link rel="stylesheet" href="{% static 'detail/css/bganim.css' %}">
<script src="https://kit.fontawesome.com/55f60ce0c2.js" crossorigin="anonymous"></script>

templates/detail_meta_tags.html
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{% if request.resolver_match.kwargs.search|length > 12 %}
     <title>
         Address {{request.resolver_match.kwargs.search}} | Blockchain Search Engine
     </title>
     <meta name="Description" content=" {{request.resolver_match.kwargs.search}} Using this address you can view all your transactions (received and sent) and also view and share your balance in detail..." />
     <meta name="keywords" content="bitcoin, explorer, engine, search, blockchain, crypto, currency" />
     <meta name="format-detection" content="telephone=no" />
     <meta property="og:title" content=" Address {{request.resolver_match.kwargs.search}} | Blockchain Search Engine" />
     <meta property="og:description" content="{{request.resolver_match.kwargs.search}} Using this address you can view all your transactions (received and sent) and also view and share your balance in detail..." />
{% else %}
     <title>
        Data of {{request.resolver_match.kwargs.search}} | Blockchain Search Engine
      </title>
      <meta name="Description" content=" {{request.resolver_match.kwargs.search}} Live Chart - You can see all the information about {{request.resolver_match.kwargs.search}} such as price, market value, history as well as its chart, etc. on our website." />
      <meta name="keywords" content="bitcoin, explorer, engine, search, blockchain, crypto, currency" />
      <meta name="format-detection" content="telephone=no" />
      <meta property="og:title" content="Data of {{request.resolver_match.kwargs.search}} | Blockchain Search Engine" />
      <meta property="og:description" content="{{request.resolver_match.kwargs.search}} Live Chart - You can see all the information about {{request.resolver_match.kwargs.search}} such as price, market value, history as well as its chart, etc. on our website." />
{% endif %}
      <meta name="author" content="AtomicEngine.pythonanywhere.com" />
      <meta property="og:site_name" content="Blockchain Search Engine" />
      <meta property="og:type" content="website" />
      <meta property="og:image" content="AtomicEngine.pythonanywhere.com/static/images/yorocket-logo.webp" />
      <meta property="og:url" content="AtomicEngine.pythonanywhere.com/scan/{{request.resolver_match.kwargs.search}}" />
      <meta property="og:image:alt" content="Visit AtomicEngine.pythonanywhere.com" />

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% include "meta_tags.html" %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link rel="stylesheet" href="{% static 'css/design.css' %}">
    <style>
      @media only screen and (min-width: 800px) {
              canvas{
                background-image: url(static/images/bg-desktop.jpg);
                background-size: cover;
                filter: hue-rotate(180deg);
                animation: filter-color 10s infinite;
              }
      }
      @media only screen and (max-width: 600px) {
        p.networks {
          position: relative;
          top: 10px;
      }
    }
      @keyframes filter-color {
        0% {filter: hue-rotate(300deg);}
        50% {filter: hue-rotate(130deg);}
        100% {filter: hue-rotate(300deg);}
      }
    </style>
</head>
<body >
  <div  id="particles"></div>
  <div class="frame" >
    <header class="frame-header">
        <div class="image">
          <img class="album-artwork" src="{% static 'images/bsep.png' %}"/>
        </div>
        <div class="info">
          <div class="subtitle">◉ Blockchain Search Engine ◉<br></div>
            <!-- Price:{{response|truncatechars:15}}$</div> -->
            <p class="networks" id="test">◉ MATIC ◉ SOL ◉ BSC ◉ CARDANO ◉ BTC ◉ TRX ◉</p>
          </div>
    </header>
    <div class="frame-bg">
      <img class="bg-color album-artwork" src="https://is2-ssl.mzstatic.com/image/thumb/Music118/v4/1c/77/af/1c77af17-4ca7-1871-9d53-3683eab952c0/source/600x600bb.jpg"/>
      <img class="bg-black album-artwork" src="https://is2-ssl.mzstatic.com/image/thumb/Music118/v4/1c/77/af/1c77af17-4ca7-1871-9d53-3683eab952c0/source/600x600bb.jpg"/>
      <img class="bg-color-2 album-artwork" src="https://is2-ssl.mzstatic.com/image/thumb/Music118/v4/1c/77/af/1c77af17-4ca7-1871-9d53-3683eab952c0/source/600x600bb.jpg"/>
    </div>	
    </div>
  <form action="{% url 'scan:detail_account_address' %}" method="GET" autocomplete="off">
    <div class="wrapper">
      <div class="search-input">
        <input name="search" type="text" placeholder="Search by Address / Coins / ..." id="input_f">
        <div class="autocom-box">
        </div>
       <button class="icon" onclick="trip()"><i class="fas fa-search"></i></button>
      </div>
    </div>
  </form>
  
    <script src="{% static 'js/suggestions.js' %}"></script>
    <script src="{% static 'js/autocomplete.js' %}"></script>
    <script src="{% static 'js/atoms.js' %}"></script>

</html>

templates/meta_tags.html
<title> BSE - Blockchain Search Engine </title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="Description" content="BSE is a search engine in the field of blockchain technology ! You can check the price of the coins or your address balance. You can also view your transactions (most Networks)">
<meta name="author" content="AtomicEngine.pythonanywhere.com">
<meta name="keywords" content="bitcoin, explorer, engine, search, blockchain, crypto, currency">
<meta name="format-detection" content="telephone=no">
<meta property="og:title" content=" Blockchain Search Engine">
<meta property="og:description" content="You can check the price of the coins or your address balance. You can also view your transactions (most Networks) ">
<meta property="og:type" content="website">
<meta property="og:site_name" content="BSE">
<meta property="og:url" content="AtomicEngine.pythonanywhere.com">
<meta property="og:image" content="AtomicEngine.pythonanywhere.com">
<meta property="og:image:alt" content="Visit AtomicEngine.pythonanywhere.com">

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'scan:scanner' %}"><img src="{% static 'images/bsep.png' %}" width="35" alt="ShiboooLogo"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="#Balance">Balance</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#Transactions">Transaction</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://t.me/MiniShibaInu">Support</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="">About</a>
        </li>
      </ul>
    </div>
  </nav>